"""
Pydantic models for sensor data and API responses.
"""

from pydantic import BaseModel, Field
from typing import Optional, Dict, List
from datetime import datetime

class RoomContext(BaseModel):
    """Context generated by the required AI Scanner layer."""
    room_type: str = Field(..., description="Classified room type")
    identified_objects: List[str] = Field(default_factory=list, description="List of COCO objects detected")


class SensorReading(BaseModel):
    """Raw sensor payload as received from the Pico."""
    temperature_c: float = Field(..., description="Temperature in Celsius")
    humidity_pct: float = Field(..., description="Relative humidity percentage")
    light_lux: float = Field(..., description="Light level in lux")
    noise_db: float = Field(..., description="Noise level in decibels")
    pressure_hpa: float = Field(..., description="Atmospheric pressure in hPa")
    pm25_ugm3: float = Field(..., description="PM2.5 particulate matter in µg/m³")
    voc_ppb: float = Field(..., description="Volatile organic compounds in ppb")
    pot_pct: float = Field(0.0, description="Potentiometer setting percentage")
    timestamp_ms: Optional[int] = Field(None, description="Pico tick timestamp")


class ScoreBreakdown(BaseModel):
    """Breakdown of the final IAQ score calculation."""
    base_mlp_score: float = Field(0.0, description="Score from the Neural Network")
    voc_penalty: float = Field(0.0, description="Deduction due to VOCs")
    pm25_penalty: float = Field(0.0, description="Deduction due to Particulates")
    final_score: int = Field(0, description="Resulting clamped score")


class RoomStatus(BaseModel):
    """Full API response with sensor data + computed score."""
    reading: Optional[SensorReading] = None
    score: int = Field(0, ge=0, le=99, description="Room Health Score (1-99, 0 = no data)")
    sleep_score: int = Field(0, ge=0, le=99, description="Sleeping Conditions Score (1-99, 0 = no data)")
    work_score: int = Field(0, ge=0, le=99, description="Work Conditions Score (1-99, 0 = no data)")
    fun_score: int = Field(0, ge=0, le=99, description="Fun/Social Conditions Score (1-99, 0 = no data)")
    breakdown: Optional[ScoreBreakdown] = None
    activity_breakdowns: Dict[str, list] = Field(default_factory=dict, description="Detailed math for specialized activities")
    room_context: Optional[RoomContext] = Field(None, description="Scanner AI Layer State")
    last_updated: Optional[datetime] = None
    connected: bool = Field(False, description="Whether the serial connection is active")
